// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError('DefaultFirebaseOptions are not supported for this platform.');
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJvcQiVGgfjO-VyVX4kOo0ZvSxv-i0S8g',
    appId: '1:235390803742:web:20746318f3b586119eb30f',
    messagingSenderId: '235390803742',
    projectId: 'petadoptingapp',
    authDomain: 'petadoptingapp.firebaseapp.com',
    storageBucket: 'petadoptingapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY6QAjqPSkE1MEcGwHcT4PrxofNyVdKMU',
    appId: '1:235390803742:android:13343ef048b16fb59eb30f',
    messagingSenderId: '235390803742',
    projectId: 'petadoptingapp',
    storageBucket: 'petadoptingapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCPKlER1IPLHlZH-NMoKzCqJ3UeAUCuuTM',
    appId: '1:235390803742:ios:085aa8cca6cb63ac9eb30f',
    messagingSenderId: '235390803742',
    projectId: 'petadoptingapp',
    storageBucket: 'petadoptingapp.firebasestorage.app',
    iosBundleId: 'com.example.pummelTheFish',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCPKlER1IPLHlZH-NMoKzCqJ3UeAUCuuTM',
    appId: '1:235390803742:ios:085aa8cca6cb63ac9eb30f',
    messagingSenderId: '235390803742',
    projectId: 'petadoptingapp',
    storageBucket: 'petadoptingapp.firebasestorage.app',
    iosBundleId: 'com.example.pummelTheFish',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJvcQiVGgfjO-VyVX4kOo0ZvSxv-i0S8g',
    appId: '1:235390803742:web:11233dfe662b5cac9eb30f',
    messagingSenderId: '235390803742',
    projectId: 'petadoptingapp',
    authDomain: 'petadoptingapp.firebaseapp.com',
    storageBucket: 'petadoptingapp.firebasestorage.app',
  );
}
